---
abstract: 'Business::MaxMind - Access MaxMind minFraud, Telephone and Location verification services'
author:
  - 'TJ Mather <tjmather@maxmind.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-MaxMind
no_index:
  directory:
    - t
    - inc
requires:
  LWP::UserAgent: 0
  URI: 1.36
version: 1.54
